### PR TITLE
Custom protocol

### PR DESCRIPTION
**Pull request by divagant-martian**

### CODE REVIEW

**Review by AgeManning — APPROVED** [review]
This looks like a simpler approach to me.

**Comment by AgeManning** [comment]
Yep. This is has not been merged yet as I understand @divagant-martian might be improving on this slightly. 

Will wait for her response before merging.

**Comment by divagant-martian** [comment]
Yeah, have not found time for this yet. Let's merge this if by monday I have still not found time for it

**Comment by divagant-martian** [comment]
I explored the other option which involved threading down a trait with associated constants. This change however looks good enough for us and does not pollute the code with a trait that is only necessary at the `PacketHeader` level , so we are opting for using the current solution

**Comment by LNSD** [comment]
It works for me too. Thanks 🙏

**Comment by divagant-martian** [comment]
@LNSD this change created some issues, please have a look at https://github.com/sigp/discv5/pull/163 and let me know if this works for you. The main difference is that the protocol id and version will be moved to compile time. From [this old comment](https://github.com/sigp/discv5/pull/157#pullrequestreview-1242766829) I assume this will still be a solution for your needs

**Pull request merged**
