### PR TITLE
Add CI test for checking for unused dependencies

### PR DESCRIPTION
**Pull request by KolbyML**
Fixes https://github.com/sigp/discv5/issues/177

### CODE REVIEW

**Comment by KolbyML** [comment]
so sad

**Comment by divagant-martian** [comment]
Oh sorry we didn't see this before, a review request would have helped, but don't be sad! low hanging fruits pop often

**Comment by KolbyML** [comment]
@divagant-martian I don't have permissions to make a review required

**Comment by divagant-martian** [comment]
oh that's unexpected, feel free to tag age or myself in any case

**Comment by KolbyML** [comment]
sounds good 👍

**Pull request closed without merging**
