### PR TITLE
Add serde to Pong struct

### PR DESCRIPTION
**Pull request by KolbyML**
## Description

Add serde to Pong struct

## Notes & open questions

No rush to get this out, I just think this could be useful

## Change checklist

- [x] Self-review
- [ ] Documentation updates if relevant
- [ ] Tests if relevant

### CODE REVIEW

**Comment by divagant-martian** [comment]
is there a use case for this? Otherwise I don't think it's of use to include. Not against the change on itself -it seems simple and well implemented-, but there are plenty types that could derive `Serialize` and `Deserialiaze` that don't do since there is no need. So, why pong? it's particularly ephemeral

**Comment by KolbyML** [comment]
I want to use the struct as the return type for one of our jsonrpsee endpoints which is calls send_ping and returns Pong. I can always just copy paste this struct then .into() what I get from sigp/discv5, but I thought it was clearer and less duplicate code to just add serde here.

**Comment by divagant-martian** [comment]
could you please check what other public types trin would use in the json rpc to do this in a batch? Easier to understand as a future reader of the git history if they are all added together instead of one by one

**Comment by AgeManning** [comment]
Yeah I agree. If we are going to implement a serialize/deserialze trait on our RPC, we should not do it ad-hoc. If we are going to implement on one, we should at least implement it on all.

**Comment by divagant-martian** [comment]
closing this as stale

**Pull request closed without merging**
