### PR TITLE
Fix some miscellaneous things

### PR DESCRIPTION
**Pull request by jtraglia**
### Summary

Fixing some things that IntelliJ pointed out:

* Replace `assert!(a == b)` with `assert_eq!(a, b)`.
* Remove needless lifetimes from `get_bucket`.
* Remove unnecessary qualified paths.
* Fix some typos.

### CODE REVIEW

**Review by divagant-martian — APPROVED** [review]
LGTM!

**Comment by jtraglia** [comment]
Alright, sorry about all of the clippy CI check failures. Could I get some help with these?

```
warning: `Box::new(_)` of default value
   --> src/config.rs:320:41
    |
320 |             self.config.executor = Some(Box::new(crate::executor::TokioExecutor::default()));
    |                                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    |
    = help: use `Box::default()` instead
    = help: for further information visit https://rust-lang.github.io/rust-clippy/master/index.html#box_default
    = note: `-D clippy::box-default` implied by `-D warnings`

warning: `Box::new(_)` of default value
   --> src/discv5.rs:101:36
    |
101 |             config.executor = Some(Box::new(crate::executor::TokioExecutor::default()));
    |                                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    |
    = help: use `Box::default()` instead
    = help: for further information visit https://rust-lang.github.io/rust-clippy/master/index.html#box_default

warning: `Box::new(_)` of default value
  --> src/service/test.rs:47:19
   |
47 |         .executor(Box::new(crate::executor::TokioExecutor::default()))
   |                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
   |
   = help: use `Box::default()` instead
   = help: for further information visit https://rust-lang.github.io/rust-clippy/master/index.html#box_default
```

Replacing those with `Box::default()` doesn't seem to work. Not sure what to do here.

**Comment by divagant-martian** [comment]
CI seems happy

**Comment by jtraglia** [comment]
Okay great. Thanks!

**Pull request merged**
